# Use the official Node.js image as a base
FROM node:22

# Set working directory
WORKDIR /app

# Install dependencies
COPY frontend/package.json frontend/yarn.lock /app/
RUN yarn install

# Copy the project files
COPY frontend/ /app/

# Expose the port for Next.js development server
EXPOSE 3000

# Run the Next.js development server
CMD ["yarn", "dev"]