services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
      args:
        AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
        AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
        AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
        FORMAT_OUTPUT: ${FORMAT_OUTPUT}
    env_file:
      - ./backend/settings/.env
    image: ${PROJECT_NAME_BACKEND}:${TAG}
    container_name: ${PROJECT_NAME_BACKEND}
    ports:
      - '8000:8000'

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    env_file:
      - ./frontend/.env
    image: ${PROJECT_NAME_FRONTEND}:${TAG}
    container_name: ${PROJECT_NAME_FRONTEND}
    ports:
      - '80:80'
    depends_on:
      - backend