name: Python Lint

on:
  pull_request:
    branches:
      - main

jobs:
  lint-server:
    name: 🔦 Black - Server Linting
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: psf/black@stable
